HealthcareBase/HealthcareBase.csproj
HealthcareIS.sln
HospitalWebApp/Controllers/WeatherForecastController.cs
HospitalWebApp/HospitalWebApp.csproj
HospitalWebApp/Program.cs
HospitalWebApp/Properties/launchSettings.json
HospitalWebApp/Startup.cs
HospitalWebApp/WeatherForecast.cs
HospitalWebApp/appsettings.Development.json
HospitalWebApp/appsettings.json
WPFHospitalEditor/App.xaml
WPFHospitalEditor/App.xaml.cs
WPFHospitalEditor/AssemblyInfo.cs
WPFHospitalEditor/MainWindow.xaml
WPFHospitalEditor/MainWindow.xaml.cs
WPFHospitalEditor/WPFHospitalEditor.csproj

Fixes #1 
A solution and three projects, needed by whole @PSW-2020-ORG9/developers team, were created. That includes:
- An empty Class Library Project where the SiMS base shall be imported
- An empty WPF .NET Core Project for the Hospital Editor
- An ASP.NET Core Project with API template for the Hospital Web App

Created starting projects

---

DevOps/pr_validation.yml

Dummy PR validation

---

WPFHospitalEditor/MapObjectModel/AllConstants.cs
WPFHospitalEditor/MapObjectModel/MapObject.cs
WPFHospitalEditor/MapObjectModel/MapObjectColors.cs
WPFHospitalEditor/MapObjectModel/MapObjectCoordinates.cs
WPFHospitalEditor/MapObjectModel/MapObjectDimensions.cs
WPFHospitalEditor/MapObjectModel/MapObjectDoor.cs
WPFHospitalEditor/MapObjectModel/MapObjectDoorOrientation.cs
WPFHospitalEditor/MapObjectModel/MapObjectMetrics.cs
WPFHospitalEditor/MapObjectModel/MapObjectType.cs

MapObject model and its related classes.

Feature ge mapobject model

---

HospitalWebApp/Startup.cs

Using database secrets from environment

---

HealthcareBase/Model/Database/MySqlContext.cs
HealthcareBase/Model/HospitalResources/Department.cs
HealthcareBase/Model/HospitalResources/EquipmentType.cs
HealthcareBase/Model/HospitalResources/EquipmentUnit.cs
HealthcareBase/Model/HospitalResources/Room.cs
HealthcareBase/Model/HospitalResources/RoomType.cs
HealthcareBase/Model/Schedule/Hospitalizations/Hospitalization.cs
HealthcareBase/Model/Schedule/Hospitalizations/HospitalizationType.cs
HealthcareBase/Model/Schedule/Procedures/ProcedureType.cs
HealthcareBase/Service/HospitalResourcesService/EquipmentService/EquipmentService.cs
HealthcareBase/Service/HospitalResourcesService/EquipmentService/EquipmentTypeService.cs
HealthcareBase/Service/HospitalResourcesService/RoomService/DepartmentService.cs
HealthcareBase/Service/HospitalResourcesService/RoomService/RoomService.cs
HealthcareBase/Service/ScheduleService/ScheduleFittingService/PreferenceToResourceConverter.cs
HealthcareBase/Service/ScheduleService/Validators/HospitalizationScheduleComplianceValidator.cs
HealthcareBase/Service/ScheduleService/Validators/HospitalizationValidator.cs
HealthcareBase/Service/ScheduleService/Validators/ProcedureValidator.cs
HealthcareBase/Service/UsersService/EmployeeService/DoctorService.cs

Rooms, Hospitalization, EquipmentType, EquipmentUnit, Departments.

Model refactor for [Room, Hospitalization, Equipment]

---

HospitalWebApp/HospitalWebApp.csproj

needed in order for pipeline agent to package web project

HospitalWebApp should be packable

---

WPFHospitalEditor/AdditionalInformation.xaml
WPFHospitalEditor/AdditionalInformation.xaml.cs
WPFHospitalEditor/App.xaml
WPFHospitalEditor/Building.xaml.cs
WPFHospitalEditor/DynamicGridControl.xaml
WPFHospitalEditor/DynamicGridControl.xaml.cs
WPFHospitalEditor/EquipmentWindow.xaml
WPFHospitalEditor/EquipmentWindow.xaml.cs
WPFHospitalEditor/Repository/Data/AllMapObjects.json

Refactoring ge 44 defining a form for displaying content

---

DevOps/ci/build-and-static-anal.yml

properly publish HospitalWebApp

---

DevOps/pr_validation.yml

temporary solution until unit tests projects are renamed and synced

PR val temp solution ignore Integration Tests

---

DevOps/ci/build-and-static-anal.yml

Since PR validation already performs Unit tests, running them here is unnecessary (double job)

CI remove unit testing

---

db.ps1

Provide easy and relatively fast switch between current(latest), test and dev DB environment for Developers

db script for switching db env

---

HealthcareBase/Repository/HospitalResourcesRepository/EquipmentSqlRepository.cs
HealthcareBase/Repository/MedicationRepository/MedicationSqlRepository.cs

Fixed Medication and Equipment sqlRepositories. They now implement interfaces which they should.

implemented interfaces in medication and sql repositories

---

HealthcareBase/Service/MedicationService/Interface/IMedicationService.cs
HealthcareBase/Service/MedicationService/MedicationService.cs
HospitalWebApp/Controllers/Interface/IMedicationController.cs
HospitalWebApp/Controllers/MedicationController.cs
WPFHospitalEditor/Controller/Interface/IMedicationServerController.cs
WPFHospitalEditor/Controller/MedicationServerController.cs
WPFHospitalEditor/HospitalMap.xaml
WPFHospitalEditor/HospitalMap.xaml.cs
WPFHospitalEditor/Repository/Data/AllMapObjects.json
WPFHospitalEditor/SearchResultDialog.xaml.cs
WPFHospitalEditor/Service/Interface/IMedicationServerService.cs
WPFHospitalEditor/Service/MedicationServerService.cs

Basic search for medication - users can search medication by selecting medication name from the combo box. Result displays location of the medication and its quantity inside of that map object(room).
Advanced search for medication - users can click on selected map object and display its location on hospital map (jump to exact building and floor). 
For now, because medication doesn't have any connections with rooms in database, it is displayed ("stored") only in storage room and our product owner is okay with that.

Feature ge medication basic and advanced search

---

DevOps/docker/FrontDockerfile

all hail the heroku port variable

---

HealthcareBase/Model/Schedule/SchedulingPreferences/RecommendationDto.cs
HealthcareBase/Service/ScheduleService/ProcedureService/ExaminationService.cs
HealthcareBase/Service/UsersService/EmployeeService/DoctorService.cs
HealthcareBase/Service/UsersService/EmployeeService/IDoctorService.cs
HospitalWebApp/Controllers/DoctorController.cs
HospitalWebApp/Controllers/ExaminationController.cs
WPFHospitalEditor/AllConstants.cs
WPFHospitalEditor/Controller/DoctorServerController.cs
WPFHospitalEditor/Controller/Interface/IDoctorServerController.cs
WPFHospitalEditor/Controller/Interface/ISchedulingServerController.cs
WPFHospitalEditor/Controller/SchedulingServerController.cs
WPFHospitalEditor/HospitalMap.xaml
WPFHospitalEditor/HospitalMap.xaml.cs
WPFHospitalEditor/SearchResultDialog.xaml
WPFHospitalEditor/SearchResultDialog.xaml.cs
WPFHospitalEditor/SearchType.cs
WPFHospitalEditor/Service/DoctorServerService.cs
WPFHospitalEditor/Service/Interface/IDoctorServerService.cs
WPFHospitalEditor/Service/Interface/ISchedulingServerService.cs
WPFHospitalEditor/Service/SchedulingServerService.cs

Basic and advanced appointment search.
Secretary  selects doctor for regular examination, picks start and end date and chooses priority for searching(Doctor/Time).
When list of appointments is displayed, secretary can click on room that is available for the appointment and can display it on hospital map.

Feature ge basic and advanced appointment search

---

HealthcareBase/Model/Database/MySqlContext.cs
HospitalWebApp/Controllers/ExaminationController.cs
HospitalWebApp/Controllers/MedicationController.cs
HospitalWebApp/Controllers/PatientController.cs
WPFHospitalEditor/Controller/ExaminationServerController.cs
WPFHospitalEditor/Controller/Interface/IExaminationServerController.cs
WPFHospitalEditor/Controller/Interface/IPatientServerController.cs
WPFHospitalEditor/Controller/PatientServerController.cs
WPFHospitalEditor/HospitalMap.xaml.cs
WPFHospitalEditor/ScheduleWindow.xaml
WPFHospitalEditor/ScheduleWindow.xaml.cs
WPFHospitalEditor/SearchResultDialog.xaml
WPFHospitalEditor/SearchResultDialog.xaml.cs
WPFHospitalEditor/Service/ExaminationServerService.cs
WPFHospitalEditor/Service/Interface/IExaminationServerService.cs
WPFHospitalEditor/Service/Interface/IPatientServerService.cs
WPFHospitalEditor/Service/PatientServerService.cs

Secretary can choose one of the appointment search results and schedule an examination.
After choosing appointment, he selects patient and then schedules an examination
There is a button "Schedule" for each search result.

Feature ge appointment scheduling

---

WPFHospitalEditor/Building.xaml.cs
WPFHospitalEditor/Controller/Interface/IMapObjectController.cs
WPFHospitalEditor/Controller/MapObjectController.cs
WPFHospitalEditor/HospitalMap.xaml
WPFHospitalEditor/HospitalMap.xaml.cs
WPFHospitalEditor/Repository/IMapObjectRepository.cs
WPFHospitalEditor/Repository/MapObjectRepository.cs
WPFHospitalEditor/SearchResultDialog.xaml.cs
WPFHospitalEditor/Service/Interface/IMapObjectService.cs
WPFHospitalEditor/Service/MapObjectService.cs

Loading of certain building's map objects is moved to repository. This changes are also implemented in SearchResultDialog class.
Map objects of advanced search are now colored in red just before they are shown in building.

Refactor: Building mapobjects

---

WPFHospitalEditor/AdditionalInformation.xaml.cs
WPFHospitalEditor/Building.xaml.cs
WPFHospitalEditor/HospitalMap.xaml.cs
WPFHospitalEditor/MapObjectModel/MapObject.cs
WPFHospitalEditor/MapObjectModel/MapObjectDescription.cs
WPFHospitalEditor/Repository/Data/AllMapObjects.json
WPFHospitalEditor/Repository/MapObjectRepository.cs
WPFHospitalEditor/SearchResultDialog.xaml.cs
WPFHospitalEditorUnitTests/FindMapObjectsTest.cs
WPFHospitalEditorUnitTests/SearchMapObjectsOnHospitalMap.cs

Map objects now have Description with its BuildingId, Floor Number and Information instead of all being stored in Description string.
Fix #107

Refactor data structure for mapobject description #107

---

HospitalWebApp/Controllers/DoctorController.cs
HospitalWebApp/Controllers/MedicationController.cs
WPFHospitalEditor/Service/DoctorServerService.cs
WPFHospitalEditor/Service/EquipmentServerService.cs
WPFHospitalEditor/Service/EquipmentTypeServerService.cs
WPFHospitalEditor/Service/ExaminationServerService.cs
WPFHospitalEditor/Service/MedicationServerService.cs
WPFHospitalEditor/Service/PatientServerService.cs
WPFHospitalEditor/Service/SchedulingServerService.cs

Issue: Renaming REST resources 

---

OcelotApiGateway/ocelot.global.json
Schedule.API/Controllers/ExaminationController.cs

Fix: Removed authorization checks for certain controller methods.

Fix: Auth removed for gEditor controller methods

---

WPFDirector/MainWindow.xaml.cs
WPFDoctor/MainWindow.xaml.cs
WPFHospitalEditor/AdditionalInformation.xaml.cs
WPFHospitalEditor/AllConstants.cs
WPFHospitalEditor/App.xaml
WPFHospitalEditor/Building.xaml.cs
WPFHospitalEditor/HospitalMainWindow.xaml
WPFHospitalEditor/HospitalMainWindow.xaml.cs
WPFHospitalEditor/Pages/BuildingPage.xaml
WPFHospitalEditor/Pages/BuildingPage.xaml.cs
WPFHospitalEditor/Pages/HospitalMapPage.xaml
WPFHospitalEditor/Pages/HospitalMapPage.xaml.cs
WPFHospitalEditor/SearchResultDialog.xaml.cs
WPFHospitalEditor/StrategyPattern/AppointmentSearchResultDTO.cs
WPFHospitalEditor/StrategyPattern/ContentRowsStrategy.cs
WPFHospitalEditor/StrategyPattern/SearchResultDTO.cs
WPFHospitalEditor/StrategyPattern/SearchResultStrategy.cs
WPFPatient/MainWindow.xaml.cs
WPFSecretary/MainWindow.xaml.cs

Added main window
Added 2 pages(HospitalMap and Building)
Used Strategy Pattern for search

Refactored WPF application

---

OcelotApiGateway/ocelot.global.json
WPFDirector/MainWindow.xaml
WPFDirector/MainWindow.xaml.cs
WPFDoctor/MainWindow.xaml
WPFDoctor/MainWindow.xaml.cs
WPFHospitalEditor/AdditionalInformation.xaml.cs
WPFHospitalEditor/AllConstants.cs
WPFHospitalEditor/Controller/Interface/IUserServerController.cs
WPFHospitalEditor/Controller/UserServerController.cs
WPFHospitalEditor/DTOs/LoginCredentials.cs
WPFHospitalEditor/HospitalMainWindow.xaml.cs
WPFHospitalEditor/Model/LoggedUser.cs
WPFHospitalEditor/Pages/BuildingPage.xaml.cs
WPFHospitalEditor/Pages/HospitalMapPage.xaml.cs
WPFHospitalEditor/Repository/Data/AllMapObjects.json
WPFHospitalEditor/SearchResultDialog.xaml.cs
WPFHospitalEditor/Service/DoctorServerService.cs
WPFHospitalEditor/Service/EquipmentServerService.cs
WPFHospitalEditor/Service/EquipmentTypeServerService.cs
WPFHospitalEditor/Service/ExaminationServerService.cs
WPFHospitalEditor/Service/Interface/IUserServerService.cs
WPFHospitalEditor/Service/MedicationServerService.cs
WPFHospitalEditor/Service/PatientServerService.cs
WPFHospitalEditor/Service/SchedulingServerService.cs
WPFHospitalEditor/Service/UserServerService.cs
WPFPatient/MainWindow.xaml
WPFPatient/MainWindow.xaml.cs
WPFPatient/WPFPatient.csproj
WPFSecretary/MainWindow.xaml
WPFSecretary/MainWindow.xaml.cs

Implemented user login for WPF applications.
Added cookie to all HTTP requests.
Deleted Role from HospitalMapWindow.

implemented user login for WPF apps

---

WPFHospitalEditor/DTOs/RecommendationDto.cs
WPFHospitalEditor/Model/RecommendationPreference.cs
WPFHospitalEditor/Model/TimeInterval.cs
WPFHospitalEditor/ScheduleWindow.xaml.cs
WPFHospitalEditor/SearchResultDialog.xaml.cs

Appointment recommendation now works :)

fix: appointment recommendation

---

WPFHospitalEditor/AdditionalInformation.xaml.cs
WPFHospitalEditor/Exceptions/ValidationException.cs
WPFHospitalEditor/Pages/BuildingPage.xaml
WPFHospitalEditor/Pages/BuildingPage.xaml.cs
WPFHospitalEditor/SearchResultDialog.xaml.cs
WPFHospitalEditor/UserControls/LegendUC.xaml.cs

BuildingPage contained data for each floor, although only one was always displayed.

Refactoried BuildingPage and inserted validation for LegendUC

---

OcelotApiGateway/ocelot.global.json
Schedule.API/Controllers/ExaminationController.cs
Schedule.API/DTOs/EquipmentRecommendationRequestDto.cs
Schedule.API/Services/Procedures/Interface/IRecommendationService.cs
Schedule.API/Services/Procedures/RecommendationService.cs
WPFHospitalEditor/AllConstants.cs
WPFHospitalEditor/AlternativeRelocationAppointments.xaml
WPFHospitalEditor/AlternativeRelocationAppointments.xaml.cs
WPFHospitalEditor/Controller/Interface/ISchedulingServerController.cs
WPFHospitalEditor/Controller/SchedulingServerController.cs
WPFHospitalEditor/DTOs/EquipmentRecommendationRequestDto.cs
WPFHospitalEditor/EquipmentRelocation.xaml.cs
WPFHospitalEditor/SearchResultDialog.xaml
WPFHospitalEditor/SearchResultDialog.xaml.cs
WPFHospitalEditor/SearchType.cs
WPFHospitalEditor/Service/Interface/ISchedulingServerService.cs
WPFHospitalEditor/Service/SchedulingServerService.cs
WPFHospitalEditor/StrategyPattern/EquipmentRelocationSearchResultDTO.cs
WPFHospitalEditor/StrategyPattern/SearchResultStrategy.cs

With this feature director can choose and schedule closest available appointment for equipment relocation if appointment he chose is not available.

Feature: alternative relocation appointments

---

HospitalFrontend/src/views/ObservePatientExaminations.vue
OcelotApiGateway/ocelot.global.json

- Created modal view for examination reports on frontend

Examination reports view
